import { useEffect, useRef } from 'react'
import iconUrl from '../../public/icon.svg'

// The alien cat from the logo rendered as ASCII art on a canvas: the icon's
// alpha channel is sampled into a character grid once, drawn to a persistent
// layer, then kept alive by a slow matrix-style churn of glyphs and a scanning
// shimmer. Hovering opens an x-ray window that dims the surface and brightens
// the glyphs that fall on the cat skeleton (skull with eye socket and teeth,
// spine, ribcage, limbs, segmented tail), so the bones appear as highlighted
// characters within the cat itself. Append ?skeleton to the URL to display
// the full skeleton without hovering (layout review).

const RENDER_SIZE = 480
const CELL = 7
const FPS = 24
// Glyph churn rate: cells re-rolled per frame. 3 at 24fps over ~1800 cells
// turns the whole figure over in roughly 25 seconds.
const MUTATIONS_PER_FRAME = 3
// Radius of the hover x-ray window, in render coordinates.
const XRAY_RADIUS = 92
// One-time intro: a diagonal x-ray band sweeps top-left to bottom-right on load
// (like a shine) so the skeleton reveal is noticeable without hovering.
// INTRO_BAND is the band's half-width; the sweep cancels as soon as the cursor
// reaches the cat.
const INTRO_DELAY = 350
const INTRO_DURATION = 4000
const INTRO_BAND = 90

// Glyph pools by intensity band; a random pick within the band keeps the
// shading readable while the texture stays varied and code-flavored.
const LIGHT = "·:;,'^~"
const MID = '=+<>/\\()[]?!'
const DENSE = '#%@&$8{}*'

function glyphFor(intensity: number): string {
  const pool = intensity > 0.75 ? DENSE : intensity > 0.45 ? MID : LIGHT
  return pool[Math.floor(Math.random() * pool.length)]
}

function baseFill(intensity: number): string {
  return `rgba(134, 239, 172, ${0.12 + intensity * 0.38})`
}

const easeInOutCubic = (x: number): number => (x < 0.5 ? 4 * x * x * x : 1 - (-2 * x + 2) ** 3 / 2)

interface Cell {
  x: number
  y: number
  char: string
  intensity: number
}

// The skeleton sampled onto the glyph grid, generated by
// scripts/skeleton-map.py from a drawn cat-skeleton image: each row is one
// grid row of cells starting BONE_MAP_TOP rows down, '.' is no bone and a
// hex digit is bone coverage out of 15. Regenerate with:
//   python3 scripts/skeleton-map.py <skeleton.png>
const BONE_MAP_TOP = 8
const BONE_MAP = [
  '.................4662',
  '..............cfffffffa',
  '............8fffffffffff',
  '...........affffffffffffb',
  '..........6ffffffffffffff',
  '..........ff3..9fffffffff3',
  '..........ff...2effffffff4',
  '.........7ff...afffffffff',
  '.........fff3.3fff7bffffc',
  '........bfffffffafdf9ff8',
  '.........ffffff8dfff.abe',
  '........6ffffff6ffff.fff2',
  '........affabaeffffd.ffff',
  '.........af8fffffe...fff5',
  '.........9ffffff4....fffa',
  '..........287........ffcd',
  '....................3fff7',
  '....................2ffbf',
  '.....................fdaff566',
  '.....................9fffffe4',
  '....................3effffff9f3........................3',
  '..................3f9ffffffff..........................f',
  '..................f7dffffffffcf6......................5f',
  '.................8b6ffffffff9f487.....................b8',
  '...............cfff8ffffff5fcfff6.....................e',
  '...............ffe.fffff2fcfefaffe....................f',
  '...............fb.ffff7f7fecfffffff...................f',
  '...............f6.bfff.f5feaf8ffcff86................5f',
  '..............2ffffff.2f.fabf6f9fbeff4...............3a',
  '...............f5fffa.ef.f5ef6f3ffefff5..............7f',
  '...............f88ff65f57f.fd6f.f7f9ffed..............f',
  '...............ffbffefb.ff.f6bf3f3ffdfff3.............f',
  '...............7ff6ff..6f34f.fe7f3f7fcffcf............f',
  '................fe.efa5fc.ff.f7cf4f3f35fff.3..........b',
  '................6ff9ffbe.3f64f.fd7f3f.4fffff..........fa',
  '.................8f96ff.2ff.ff.f5dd8c...8fff..........be',
  '..................bf8ff8ff.3f57f.f4d....6dfffa........6f',
  '...................7fbff6..fe.f95f.2.....2fff7........3f',
  '.....................3ffcced.ff4f3........affaa........b3',
  '......................ffff6ffd.7...........cfff........fb',
  '......................a8ff.................dffba.......dd',
  '......................fffa..................6fffa......8f',
  '......................fff...................4ffff......8f',
  '......................fff..........ff7......3fffe......3b',
  '......................fef........9cffff9.....fff8......8f',
  '......................faf........ffffffffa...fff7......4f',
  '......................f8e........afef62cfffd3cffb......5f',
  '.....................2fbb.........bffff..afffffff......af',
  '.....................5fe8.........4fffcf...ffffef8.....9e',
  '.....................aff6...........effcd..3bf9ffa.....f6',
  '.....................fff5............6ffda..f3.ff6.....f4',
  '.....................8fc2..............fff7.df9ff4....ff',
  '.....................7fea...............aff5.dffcf...6f8',
  '.....................cff.................5ff7...dff6bfd',
  '.....................eff...........3......7ff5...6fffb',
  '...................3fd9b..........8ff9feeebefff....32',
  '...................ecaf..........7fdfcfffffffff4',
  '...................257.............82.5...23..3',
]

function sampleCells(img: HTMLImageElement): Cell[] {
  const off = document.createElement('canvas')
  off.width = RENDER_SIZE
  off.height = RENDER_SIZE
  const ctx = off.getContext('2d', { willReadFrequently: true })
  if (!ctx) return []
  ctx.drawImage(img, 0, 0, RENDER_SIZE, RENDER_SIZE)
  const data = ctx.getImageData(0, 0, RENDER_SIZE, RENDER_SIZE).data
  const cells: Cell[] = []
  for (let y = 0; y < RENDER_SIZE; y += CELL) {
    for (let x = 0; x < RENDER_SIZE; x += CELL) {
      const px = Math.min(RENDER_SIZE - 1, x + Math.floor(CELL / 2))
      const py = Math.min(RENDER_SIZE - 1, y + Math.floor(CELL / 2))
      const idx = (py * RENDER_SIZE + px) * 4
      // White body reads at full luminance, the gray whiskers dimmer; fold
      // both into one intensity so the pools shade them differently.
      const intensity = (data[idx + 3] / 255) * (data[idx] / 255)
      if (intensity > 0.18) {
        cells.push({ x, y, char: glyphFor(intensity), intensity })
      }
    }
  }
  return cells
}

function buildLayer(cells: Cell[]): {
  layer: HTMLCanvasElement
  lctx: CanvasRenderingContext2D | null
} {
  const layer = document.createElement('canvas')
  const dpr = Math.min(window.devicePixelRatio || 1, 2)
  layer.width = RENDER_SIZE * dpr
  layer.height = RENDER_SIZE * dpr
  const lctx = layer.getContext('2d')
  if (!lctx) return { layer, lctx }
  lctx.scale(dpr, dpr)
  lctx.font = `${CELL + 1}px monospace`
  lctx.textBaseline = 'top'
  for (const c of cells) {
    lctx.fillStyle = baseFill(c.intensity)
    lctx.fillText(c.char, c.x, c.y)
  }
  return { layer, lctx }
}

export function AsciiCat({ className = '' }: { className?: string }) {
  const canvasRef = useRef<HTMLCanvasElement>(null)

  useEffect(() => {
    const canvas = canvasRef.current
    if (!canvas) return
    const ctx = canvas.getContext('2d')
    if (!ctx) return

    const dpr = Math.min(window.devicePixelRatio || 1, 2)
    canvas.width = RENDER_SIZE * dpr
    canvas.height = RENDER_SIZE * dpr
    ctx.scale(dpr, dpr)

    const reduceMotion = window.matchMedia('(prefers-reduced-motion: reduce)').matches
    // Review mode: render the entire skeleton at full strength, no hover
    // needed.
    const showFull = new URLSearchParams(window.location.search).has('skeleton')
    let raf = 0
    let last = 0
    let visible = true
    // Guards the async img.onload: under StrictMode the cleanup runs before
    // the image loads, and an unguarded onload would start an orphan RAF
    // loop fighting the remounted one (visible as rapid glyph flicker).
    let disposed = false
    let cells: Cell[] = []
    let staticLayer: HTMLCanvasElement | null = null
    let layerCtx: CanvasRenderingContext2D | null = null
    // Pointer position in canvas coordinates; null while the cursor is away.
    let pointer: { x: number; y: number } | null = null
    // One-time intro sweep: introStart is stamped on the first animated frame;
    // introDone latches once the sweep has played or the cursor reaches the cat.
    let introStart = -1
    let introDone = false
    // The skeleton sampled into the glyph grid: each entry pairs a cell with
    // how much bone covers it, so the hover highlights existing characters
    // instead of drawing a separate image.
    const boneCells: Array<{ cell: Cell; w: number }> = []

    const onPointerMove = (e: PointerEvent) => {
      const rect = canvas.getBoundingClientRect()
      const x = ((e.clientX - rect.left) / rect.width) * RENDER_SIZE
      const y = ((e.clientY - rect.top) / rect.height) * RENDER_SIZE
      pointer =
        x > -XRAY_RADIUS &&
        x < RENDER_SIZE + XRAY_RADIUS &&
        y > -XRAY_RADIUS &&
        y < RENDER_SIZE + XRAY_RADIUS
          ? { x, y }
          : null
      // Cursor reached the cat: hand over to hover and stop the auto-sweep.
      if (pointer) introDone = true
    }
    window.addEventListener('pointermove', onPointerMove)

    // Matrix churn: re-roll a few random cells per frame in place on the
    // persistent layer, so letters keep slowly changing across the figure.
    const mutate = () => {
      if (!layerCtx) return
      for (let k = 0; k < MUTATIONS_PER_FRAME; k++) {
        const c = cells[Math.floor(Math.random() * cells.length)]
        if (!c) continue
        c.char = glyphFor(c.intensity)
        layerCtx.clearRect(c.x - 1, c.y - 1, CELL + 2, CELL + 2)
        layerCtx.fillStyle = baseFill(c.intensity)
        layerCtx.fillText(c.char, c.x, c.y)
      }
    }

    const draw = (t: number) => {
      if (!staticLayer) return
      ctx.clearRect(0, 0, RENDER_SIZE, RENDER_SIZE)
      ctx.drawImage(staticLayer, 0, 0, RENDER_SIZE, RENDER_SIZE)
      if (reduceMotion && !showFull) return

      ctx.font = `${CELL + 1}px monospace`
      ctx.textBaseline = 'top'
      const half = CELL / 2

      if (introStart < 0) introStart = t
      const introElapsed = t - introStart
      if (!introDone && introElapsed >= INTRO_DELAY + INTRO_DURATION) introDone = true
      const introActive =
        !introDone &&
        !showFull &&
        pointer === null &&
        boneCells.length > 0 &&
        introElapsed >= INTRO_DELAY

      // X-ray: dim the surface, then repaint the glyphs sitting on bone in a
      // bright bone tint, so the skeleton shows up as highlighted characters.
      // Hover mode does this inside a soft radial window at the cursor;
      // review mode lights the whole figure.
      if (showFull && boneCells.length) {
        ctx.save()
        ctx.globalCompositeOperation = 'destination-out'
        ctx.fillStyle = 'rgba(0, 0, 0, 0.62)'
        ctx.fillRect(0, 0, RENDER_SIZE, RENDER_SIZE)
        ctx.restore()
        for (const { cell, w } of boneCells) {
          ctx.fillStyle = `rgba(227, 247, 234, ${w * 0.95})`
          ctx.fillText(cell.char, cell.x, cell.y)
        }
      } else if (pointer && boneCells.length) {
        ctx.save()
        ctx.globalCompositeOperation = 'destination-out'
        const hole = ctx.createRadialGradient(
          pointer.x,
          pointer.y,
          0,
          pointer.x,
          pointer.y,
          XRAY_RADIUS,
        )
        hole.addColorStop(0, 'rgba(0, 0, 0, 0.8)')
        hole.addColorStop(1, 'rgba(0, 0, 0, 0)')
        ctx.fillStyle = hole
        ctx.beginPath()
        ctx.arc(pointer.x, pointer.y, XRAY_RADIUS, 0, Math.PI * 2)
        ctx.fill()
        ctx.restore()

        for (const { cell, w } of boneCells) {
          const d = Math.hypot(cell.x + half - pointer.x, cell.y + half - pointer.y)
          if (d >= XRAY_RADIUS) continue
          // Falloff shaped like the old radial mask: strong at the center,
          // about half strength at 70% radius, gone at the rim.
          const f = 1 - (d / XRAY_RADIUS) ** 2
          ctx.fillStyle = `rgba(227, 247, 234, ${w * f * 0.95})`
          ctx.fillText(cell.char, cell.x, cell.y)
        }
      } else if (introActive) {
        // One-time intro: a diagonal x-ray band sweeps top-left to bottom-right
        // like a shine, lighting the bones it crosses. Position along the sweep
        // is the line x + y = sweep; distance to a cell is measured perpendicular
        // to it (divide by sqrt(2)).
        const eased = easeInOutCubic((introElapsed - INTRO_DELAY) / INTRO_DURATION)
        const bandDiag = INTRO_BAND * Math.SQRT2
        const sweep = -bandDiag + eased * (2 * RENDER_SIZE + 2 * bandDiag)
        const c = sweep / 2
        const off = INTRO_BAND / Math.SQRT2
        ctx.save()
        ctx.globalCompositeOperation = 'destination-out'
        const band = ctx.createLinearGradient(c - off, c - off, c + off, c + off)
        band.addColorStop(0, 'rgba(0, 0, 0, 0)')
        band.addColorStop(0.5, 'rgba(0, 0, 0, 0.8)')
        band.addColorStop(1, 'rgba(0, 0, 0, 0)')
        ctx.fillStyle = band
        ctx.fillRect(0, 0, RENDER_SIZE, RENDER_SIZE)
        ctx.restore()
        for (const { cell, w } of boneCells) {
          const d = Math.abs(cell.x + half + cell.y + half - sweep) / Math.SQRT2
          if (d >= INTRO_BAND) continue
          const f = 1 - (d / INTRO_BAND) ** 2
          ctx.fillStyle = `rgba(227, 247, 234, ${w * f * 0.95})`
          ctx.fillText(cell.char, cell.x, cell.y)
        }
      }

      // Scanning shimmer: a soft light band sweeping down the glyphs.
      const bandY = (((t / 1000) * 46) % (RENDER_SIZE + 240)) - 120
      ctx.save()
      ctx.globalCompositeOperation = 'source-atop'
      const grad = ctx.createLinearGradient(0, bandY - 90, 0, bandY + 90)
      grad.addColorStop(0, 'rgba(187, 247, 208, 0)')
      grad.addColorStop(0.5, 'rgba(187, 247, 208, 0.28)')
      grad.addColorStop(1, 'rgba(187, 247, 208, 0)')
      ctx.fillStyle = grad
      ctx.fillRect(0, bandY - 90, RENDER_SIZE, 180)
      ctx.restore()
    }

    const loop = (t: number) => {
      raf = requestAnimationFrame(loop)
      if (!visible || t - last < 1000 / FPS) return
      last = t
      mutate()
      draw(t)
    }

    const io = new IntersectionObserver(([entry]) => {
      visible = entry.isIntersecting
    })
    io.observe(canvas)

    const img = new Image()
    img.src = iconUrl
    img.onload = () => {
      if (disposed) return
      cells = sampleCells(img)

      // Pair each BONE_MAP weight with the glyph cell at its grid position;
      // map positions with no sampled cell (outside the silhouette) are
      // skipped.
      const cellMap = new Map(cells.map((c) => [`${c.x},${c.y}`, c]))
      BONE_MAP.forEach((row, r) => {
        const y = (BONE_MAP_TOP + r) * CELL
        for (let gx = 0; gx < row.length; gx++) {
          if (row[gx] === '.') continue
          const cell = cellMap.get(`${gx * CELL},${y}`)
          if (cell) boneCells.push({ cell, w: parseInt(row[gx], 16) / 15 })
        }
      })

      const built = buildLayer(cells)
      staticLayer = built.layer
      layerCtx = built.lctx
      if (reduceMotion && !showFull) {
        draw(0)
      } else {
        raf = requestAnimationFrame(loop)
      }
    }

    return () => {
      disposed = true
      cancelAnimationFrame(raf)
      io.disconnect()
      window.removeEventListener('pointermove', onPointerMove)
    }
  }, [])

  return (
    <canvas
      ref={canvasRef}
      aria-hidden
      className={className}
      style={{ width: RENDER_SIZE, height: RENDER_SIZE }}
    />
  )
}
